version: '3'
services:
  so:
    image: kali-so
    build:
      context: .
      dockerfile: ./provision/Dockerfile
    stdin_open: true
    tty: true
    environment:
      - SHODAN_API_KEY=$SHODAN_API_KEY
    env_file:
      - .env
    networks:
      - kali-net
    volumes:
      - kali-vol:/usr/src

volumes:
  kali-vol:


networks:
  kali-net:
